In [ ]:
import random
import numpy as np

phid = [1, 0, 1]

def reduce(p):
    global phid
    p[:] = [x % q for x in p]
    # print(p)
    Q, R = np.polydiv(p, phid)
    return R

def recurse(pos, d, q, myPol, polynomials):
#     global polynomials
    if pos == d+1:
        # print(myPol)
        newList = [int(x) for x in myPol]
        newList = reduce(newList)
        polynomials.append(newList)
        return
    for i in range (0, q):
        myPol.append(i)
        recurse(pos+1, d, q, myPol, polynomials)
        myPol.pop()

def genPolynomials(q, d, polynomials):
    myPol = []
    recurse(0, d, q, myPol, polynomials)
    
def genProbabilities():
    global probabilities
    sum = 0
    for i in range (-1*B+1, B):
        x = exp**(-pi*(i**2)/sigma**2)
        probabilities.append(x)
        sum += x
    probabilities[:] = [x / sum for x in probabilities]
    
def chikey():
    coeff = np.array([random.randint(1,q-1) for i in range((d>>1)+1)])
    return coeff
    
def ParamsGen():
    d = 4
    polynomials = []
    q = 13
    t = 7
    genPolynomials(q, d/2, polynomials)
    return d, polynomials, q, t

def inverse(f, polynomials):
    for p in polynomials:
        f_f_inv = (reduce(np.polymul(p, f))).tolist()
        if f_f_inv == [1]:
#             print(p)
            return p
    return [-1]

def KeyGen(d, polynomials, q, t):
    global phid
    f_prime = chikey().tolist()
    g = chikey().tolist()
    f = []
    f = [x*t for x in f_prime]
    f[-1] += 1
    reduce(f)
    
    f_inv = []
    while True:
        f_inv = (inverse(f, polynomials))
        if f_inv != [-1]:
            break
    
    h = reduce(np.polymul(g, f_inv))
    h_prime = [x*t for x in h]
    h = reduce(h_prime)
    
    return f_prime, g, f_inv, reduce(h.tolist()), reduce(f)
# print(len(polynomials))

# print("Enter polynomial to find inverse")

# def keygen(d, q, t, chikey, chierr):

# def encrypt(h, m):

# def decrypt(f, c):

# for p in polynomials:
#     # print(p)
#     f_f_inv = (reduce(np.polymul(p, message))).tolist()
#     if f_f_inv == [1]:
#         print(p)
#         break

In [ ]:
d, polynomials, q, t = ParamsGen()
print(d, phid, q, t)

f_prime, g, f_inv, h, f = KeyGen(d, polynomials, q, t)
f = reduce(f)
print(f_prime, g, f_inv, h, f)

In [145]:
probabilities = []
temp = [1, 2, 3]
temp[-1] += 1

In [45]:
temp

[1, 2, 4]

In [57]:
chikey()

array([5, 7, 9, 6, 4])

In [58]:
chikey().tolist()

[1, 5, 8, 1, 10]

In [70]:
reduce([-5, 5])

array([8., 5.])

In [127]:
reduce([7, -7])

array([7., 6.])